pipeline {
    agent {
        label 'ansible_docker'
        }

    stages {
        stage('Git checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Perovss/Jenkins.git'
            }
        }
        stage('install Roles') {
            steps {
                sh 'ansible-galaxy install -r requirements.yml -p roles'
            }
        }
        stage('Run playbook') {
            steps {
                sh 'ansible-playbook site.yml -i inventory/prod.yml'
            }
        }
    }

}
